// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package bot_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BotClient is the client API for Bot service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BotClient interface {
	GetBalance(ctx context.Context, in *PaymentSystemCurrencyRequest, opts ...grpc.CallOption) (*BalanceResponse, error)
	GetUserAddress(ctx context.Context, in *PaymentSystemCurrencyUserRequest, opts ...grpc.CallOption) (*GetUserAddressResponse, error)
	GetUserBalance(ctx context.Context, in *PaymentSystemCurrencyUserRequest, opts ...grpc.CallOption) (*BalanceResponse, error)
	GetIncomeTransaction(ctx context.Context, in *GetIncomeTransactionRequest, opts ...grpc.CallOption) (*GetIncomeTransactionResponse, error)
	GetIncomeTransactions(ctx context.Context, in *GetIncomeTransactionsRequest, opts ...grpc.CallOption) (*GetIncomeTransactionResponse, error)
}

type botClient struct {
	cc grpc.ClientConnInterface
}

func NewBotClient(cc grpc.ClientConnInterface) BotClient {
	return &botClient{cc}
}

func (c *botClient) GetBalance(ctx context.Context, in *PaymentSystemCurrencyRequest, opts ...grpc.CallOption) (*BalanceResponse, error) {
	out := new(BalanceResponse)
	err := c.cc.Invoke(ctx, "/logmesh.bot.v1.Bot/GetBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botClient) GetUserAddress(ctx context.Context, in *PaymentSystemCurrencyUserRequest, opts ...grpc.CallOption) (*GetUserAddressResponse, error) {
	out := new(GetUserAddressResponse)
	err := c.cc.Invoke(ctx, "/logmesh.bot.v1.Bot/GetUserAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botClient) GetUserBalance(ctx context.Context, in *PaymentSystemCurrencyUserRequest, opts ...grpc.CallOption) (*BalanceResponse, error) {
	out := new(BalanceResponse)
	err := c.cc.Invoke(ctx, "/logmesh.bot.v1.Bot/GetUserBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botClient) GetIncomeTransaction(ctx context.Context, in *GetIncomeTransactionRequest, opts ...grpc.CallOption) (*GetIncomeTransactionResponse, error) {
	out := new(GetIncomeTransactionResponse)
	err := c.cc.Invoke(ctx, "/logmesh.bot.v1.Bot/GetIncomeTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botClient) GetIncomeTransactions(ctx context.Context, in *GetIncomeTransactionsRequest, opts ...grpc.CallOption) (*GetIncomeTransactionResponse, error) {
	out := new(GetIncomeTransactionResponse)
	err := c.cc.Invoke(ctx, "/logmesh.bot.v1.Bot/GetIncomeTransactions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BotServer is the server API for Bot service.
// All implementations must embed UnimplementedBotServer
// for forward compatibility
type BotServer interface {
	GetBalance(context.Context, *PaymentSystemCurrencyRequest) (*BalanceResponse, error)
	GetUserAddress(context.Context, *PaymentSystemCurrencyUserRequest) (*GetUserAddressResponse, error)
	GetUserBalance(context.Context, *PaymentSystemCurrencyUserRequest) (*BalanceResponse, error)
	GetIncomeTransaction(context.Context, *GetIncomeTransactionRequest) (*GetIncomeTransactionResponse, error)
	GetIncomeTransactions(context.Context, *GetIncomeTransactionsRequest) (*GetIncomeTransactionResponse, error)
	mustEmbedUnimplementedBotServer()
}

// UnimplementedBotServer must be embedded to have forward compatible implementations.
type UnimplementedBotServer struct {
}

func (UnimplementedBotServer) GetBalance(context.Context, *PaymentSystemCurrencyRequest) (*BalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedBotServer) GetUserAddress(context.Context, *PaymentSystemCurrencyUserRequest) (*GetUserAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserAddress not implemented")
}
func (UnimplementedBotServer) GetUserBalance(context.Context, *PaymentSystemCurrencyUserRequest) (*BalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserBalance not implemented")
}
func (UnimplementedBotServer) GetIncomeTransaction(context.Context, *GetIncomeTransactionRequest) (*GetIncomeTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIncomeTransaction not implemented")
}
func (UnimplementedBotServer) GetIncomeTransactions(context.Context, *GetIncomeTransactionsRequest) (*GetIncomeTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIncomeTransactions not implemented")
}
func (UnimplementedBotServer) mustEmbedUnimplementedBotServer() {}

// UnsafeBotServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BotServer will
// result in compilation errors.
type UnsafeBotServer interface {
	mustEmbedUnimplementedBotServer()
}

func RegisterBotServer(s grpc.ServiceRegistrar, srv BotServer) {
	s.RegisterService(&Bot_ServiceDesc, srv)
}

func _Bot_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentSystemCurrencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logmesh.bot.v1.Bot/GetBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).GetBalance(ctx, req.(*PaymentSystemCurrencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bot_GetUserAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentSystemCurrencyUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).GetUserAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logmesh.bot.v1.Bot/GetUserAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).GetUserAddress(ctx, req.(*PaymentSystemCurrencyUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bot_GetUserBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentSystemCurrencyUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).GetUserBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logmesh.bot.v1.Bot/GetUserBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).GetUserBalance(ctx, req.(*PaymentSystemCurrencyUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bot_GetIncomeTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIncomeTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).GetIncomeTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logmesh.bot.v1.Bot/GetIncomeTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).GetIncomeTransaction(ctx, req.(*GetIncomeTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bot_GetIncomeTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIncomeTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).GetIncomeTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logmesh.bot.v1.Bot/GetIncomeTransactions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).GetIncomeTransactions(ctx, req.(*GetIncomeTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Bot_ServiceDesc is the grpc.ServiceDesc for Bot service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bot_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logmesh.bot.v1.Bot",
	HandlerType: (*BotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBalance",
			Handler:    _Bot_GetBalance_Handler,
		},
		{
			MethodName: "GetUserAddress",
			Handler:    _Bot_GetUserAddress_Handler,
		},
		{
			MethodName: "GetUserBalance",
			Handler:    _Bot_GetUserBalance_Handler,
		},
		{
			MethodName: "GetIncomeTransaction",
			Handler:    _Bot_GetIncomeTransaction_Handler,
		},
		{
			MethodName: "GetIncomeTransactions",
			Handler:    _Bot_GetIncomeTransactions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bot.proto",
}
